url: "https://www.kaushalkafle.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Kaushal Kafle" # the name of your site, e.g. ACME Corp.
email: kafle at usf.edu
twitter_username: kaushalkafle
linkedin_username: kaflekaushal
github_username: kaflekaushal
google_scholar_username: kaushalkafle
address: Department of Computer Science and Engineering | University of South Florida
repository: kaflekaushal/kaflekaushal.github.io
# address: |
#   Department of Computer Science
#
#   College of William & Mary
#
#   251 Jamestown Road
#
#   Williamsburg
#
#   VA - 23185 USA

markdown: kramdown
